export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_REJECTED = 'FETCH_TASKS_REJECTED';
export const FETCH_TASKS_FULFILLED = 'FETCH_TASKS_FULFILLED';
export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const REOPEN_TASK = 'REOPEN_TASK';